#!/bin/bash
path=`pwd`
project_name=${PWD##*/}
echo $project_name

if [ "-jar" = $0 ]; then
    cp -rf ./plugins/example/jar/* ./
else
    cp -rf ./plugins/example/war/* ./
fi
#export CLASSPATH=${path}/plugins/ant2ide.jar
#ant -listener net.gleamynode.ant2ide.EclipseProjectGenerator "$@"
