#!/bin/bash
path=`pwd`
project_name=${PWD##*/}
echo $project_name
replace=JavaProject

if [ "-jar" = $0 ]; then
    cp -rf $path/plugins/eclipse/jar/* ./
else
    cp -rf $path/plugins/eclipse/war/. ./
    replace="DynamicWebProject"
fi
echo "s/${replace}/${project_name}/"
find .settings/ -type f |xargs sed -i "s/${replace}/${project_name}/"
sed -i "s/${replace}/${project_name}/" .project
#export CLASSPATH=${path}/plugins/ant2ide.jar
#ant -listener net.gleamynode.ant2ide.EclipseProjectGenerator "$@"
